def turletoss():
  import turtle


  wn = turtle.Screen()
  wn.title("test")
  wn.bgcolor("black")
  wn.setup(width=1200, height=800)
  wn.tracer(0)

  ###functions###
  def close_button():
      quit()

  ###pen###
  def text1():
      pen = turtle.Turtle()
      pen.speed(0)
      pen.color('white')
      pen.penup()
      pen.hideturtle()
      pen.goto(0, 260)
      pen.write('when you wake up', align='center', font=('Arial', 24, 'normal'))
      pen2 = turtle.Turtle()
      pen2.speed(0)
      pen2.color('white')
      pen2.penup()
      pen2.hideturtle()
      pen2.goto(0, -300)
      pen2.write('before 10 AM', align='center', font=('Arial', 24, 'normal'))
      eye1.shapesize(stretch_wid=5, stretch_len=3)
      eye2.shapesize(stretch_wid=3, stretch_len=5)
      mouth1 = turtle.Turtle()
      mouth1.speed(0)
      mouth1.shape("circle")
      mouth1.color("black")
      mouth1.penup()
      mouth1.goto(0, -75)
      mouth1.shapesize(stretch_wid=3, stretch_len=3)
      mouth2 = turtle.Turtle()
      mouth2.speed(0)
      mouth2.shape("circle")
      mouth2.color("black")
      mouth2.penup()
      mouth2.goto(-45, -95)
      mouth2.shapesize(stretch_wid=3, stretch_len=3)
      mouth3 = turtle.Turtle()
      mouth3.speed(0)
      mouth3.shape("circle")
      mouth3.color("black")
      mouth3.penup()
      mouth3.goto(-95, -115)
      mouth3.shapesize(stretch_wid=3, stretch_len=3)
      mouth4 = turtle.Turtle()
      mouth4.speed(0)
      mouth4.shape("circle")
      mouth4.color("black")
      mouth4.penup()
      mouth4.goto(95, -115)
      mouth4.shapesize(stretch_wid=3, stretch_len=3)

  def text2():        
      ###face###
      face = turtle.Turtle()
      face.speed(0)
      face.shape("circle")
      face.color("yellow")
      face.penup()
      face.goto(0, 0)
      face.shapesize(stretch_wid=25, stretch_len=25)
      pen = turtle.Turtle()
      pen.speed(0)
      pen.color('white')
      pen.penup()
      pen.hideturtle()
      pen.goto(0, 260)
      pen.write('test', align='center', font=('Arial', 24, 'normal'))
      pen2 = turtle.Turtle()
      pen2.speed(0)
      pen2.color('white')
      pen2.penup()
      pen2.hideturtle()
      pen2.goto(0, -300)
      pen2.write('', align='center', font=('Arial', 24, 'normal'))
      pen2.clear()
      ###eyes###
      eye1 = turtle.Turtle()
      eye1.speed(0)
      eye1.shape("circle")
      eye1.color("black")
      eye1.penup()
      eye1.goto(75, 75)
      #eye1.shapesize(stretch_wid=5, stretch_len=3)
      eye1.shapesize(stretch_wid=5, stretch_len=5)

      eye2 = turtle.Turtle()
      eye2.speed(0)
      eye2.shape("circle")
      eye2.color("black")
      eye2.penup()
      eye2.goto(-75, 75)
      #eye2.shapesize(stretch_wid=3, stretch_len=5)
      eye2.shapesize(stretch_wid=5, stretch_len=5)

      ###mouth###
      mouth1 = turtle.Turtle()
      mouth1.speed(0)
      mouth1.shape("circle")
      mouth1.color("black")
      mouth1.penup()
      mouth1.goto(0, -100)
      mouth1.shapesize(stretch_wid=3, stretch_len=3)

      mouth2 = turtle.Turtle()
      mouth2.speed(0)
      mouth2.shape("circle")
      mouth2.color("black")
      mouth2.penup()
      mouth2.goto(-45, -95)
      mouth2.shapesize(stretch_wid=3, stretch_len=3)

      mouth3 = turtle.Turtle()
      mouth3.speed(0)
      mouth3.shape("circle")
      mouth3.color("black")
      mouth3.penup()
      mouth3.goto(45, -95)
      mouth3.shapesize(stretch_wid=3, stretch_len=3)

      #mouth4 = turtle.Turtle()
      #mouth4.speed(0)
      #mouth4.shape("circle")
      #mouth4.color("black")
      #mouth4.penup()
      #mouth4.goto(-75, -60)
      #mouth4.shapesize(stretch_wid=3, stretch_len=3)

      #mouth5 = turtle.Turtle()
      #mouth5.speed(0)
      #mouth5.shape("circle")
      #mouth5.color("black")
      #mouth5.penup()
      #mouth5.goto(75, -60)
      #mouth5.shapesize(stretch_wid=3, stretch_len=3)

  face = turtle.Turtle()
  face.speed(0)
  face.shape("circle")
  face.color("yellow")
  face.penup()
  face.goto(0, 0)
  face.shapesize(stretch_wid=25, stretch_len=25)
  ###eyes###
  eye1 = turtle.Turtle()
  eye1.speed(0)
  eye1.shape("circle")
  eye1.color("black")
  eye1.penup()
  eye1.goto(75, 75)
  #eye1.shapesize(stretch_wid=5, stretch_len=3)
  eye1.shapesize(stretch_wid=5, stretch_len=5)
  eye2 = turtle.Turtle()
  eye2.speed(0)
  eye2.shape("circle")
  eye2.color("black")
  eye2.penup()
  eye2.goto(-75, 75)
  #eye2.shapesize(stretch_wid=3, stretch_len=5)
  eye2.shapesize(stretch_wid=5, stretch_len=5)
  ###mouth###
  mouth1 = turtle.Turtle()
  mouth1.speed(0)
  mouth1.shape("circle")
  mouth1.color("black")
  mouth1.penup()
  mouth1.goto(0, -100)
  mouth1.shapesize(stretch_wid=3, stretch_len=3)
  mouth2 = turtle.Turtle()
  mouth2.speed(0)
  mouth2.shape("circle")
  mouth2.color("black")
  mouth2.penup()
  mouth2.goto(-45, -95)
  mouth2.shapesize(stretch_wid=3, stretch_len=3)
  mouth3 = turtle.Turtle()
  mouth3.speed(0)
  mouth3.shape("circle")
  mouth3.color("black")
  mouth3.penup()
  mouth3.goto(45, -95)
  mouth3.shapesize(stretch_wid=3, stretch_len=3)

  ###keys###
  wn.listen()
  wn.onkeypress(close_button, 'c')
  wn.onkeypress(text1, 't')
  wn.onkeypress(text2, 'r')
  while True:
      wn.update()
